# server
server:
    run_mode: release
    http_port: 16670
    sinopac_srv_host: 172.20.10.223
    sinopac_srv_port: 13333

# database
database:
    host: 172.20.10.10
    port: 5432
    user: postgres
    passwd: asdf0000
    database: trade_agent
    time_zone: Asia/Taipei

# mqtt
mqtt:
    host: 172.20.10.225
    port: 8887
    user: toc
    passwd: asdf0000
    client_id: trade-agent
    ca_path: /configs/certs/ca_crt.pem
    cert_path: /configs/certs/client_crt.pem
    key_path: /configs/certs/client_key.pem

# switch
switch:
    simulation: true

    buy: true
    sell: true
    sell_first: true
    buy_later: true

    mean_time_forward: 1
    mean_time_reverse: 1
    forward_max: 3
    reverse_max: 3

# trade
trade:
    # unit: day
    history_close_period: 14
    history_tick_period: 8
    history_kbar_period: 8
    # unit: minute
    hold_time_from_open: 5
    # unit: hours
    total_open_time: 4.5
    # unit: seccond
    trade_in_wait_time: 45
    trade_out_wait_time: 90
    # unit: hour(s) from 9:00
    trade_in_end_time: 1.25 # 10:15
    trade_out_end_time: 4 # 13:00

# target condition
target_cond:
    limit_price_low: 10
    limit_price_high: 50
    limit_volume: 20000
    black_stock:
        - 1314
        - 2317
        - 3481
        - 3701
    black_category:
        - 17
    real_time_targets_count: 10

# analyze
analyze:
    # unit: %
    close_change_ratio_low: -2
    close_change_ratio_high: 7
    open_close_change_ratio: 5
    # unit: %
    out_in_ratio: 80
    in_out_ratio: 10
    # unit: %
    volume_pr_low: 90
    volume_pr_high: 95
    # unit: seccond
    tick_analyze_min_period: 5
    tick_analyze_max_period: 5.5
    # unit: times
    rsi_min_count: 600
    # rsi range: 0~1
    rsi_high: 0.7
    rsi_low: 0.3

# schedule cron
schedule:
    clean_event: 0 0 4 * * ?
    restart_sinopac: 0 20 1,8,15 * * ?
