// Package sinopacapi package sinopacapi
package sinopacapi

const (
	urlFetchAllStockDetail              string = "/sinopac-mq-srv/basic/stock-detail"
	urlFetchAllSnapShot                 string = "/sinopac-mq-srv/real-time/all-snapshot"
	urlFetchTSESnapShot                 string = "/sinopac-mq-srv/real-time/snapshot/tse"
	urlFetchEntireTickByStockAndDate    string = "/sinopac-mq-srv/history/tick"
	urlFetchTSETickByDate               string = "/sinopac-mq-srv/history/tick/tse"
	urlFetchKbarByDateRange             string = "/sinopac-mq-srv/history/kbar"
	urlFetchTSE001KbarByDate            string = "/sinopac-mq-srv/history/kbar/tse"
	urlFetchStockCloseMapByStockDateArr string = "/sinopac-mq-srv/history/lastcount"
	urlFetchTSE001CloseByDate           string = "/sinopac-mq-srv/history/lastcount/tse"
	urlFetchLastCloseByStockArrDateArr  string = "/sinopac-mq-srv/history/lastcount/multi-date"
	urlFetchVolumeRankByDate            string = "/sinopac-mq-srv/history/volumerank"
	urlSubBidAsk                        string = "/sinopac-mq-srv/subscribe/bid-ask"
	urlSubBidAskByStock                 string = "/sinopac-mq-srv/unsubscribe/bid-ask"
	urlUnSubscribeAllBidAsk             string = "/sinopac-mq-srv/unsubscribeall/bid-ask"
	urlSubStreamTick                    string = "/sinopac-mq-srv/subscribe/streamtick"
	urlSubStreamTickByStock             string = "/sinopac-mq-srv/unsubscribe/streamtick"
	urlUnSubscribeAllStream             string = "/sinopac-mq-srv/unsubscribeall/streamtick"
	urlPlaceOrderBuy                    string = "/sinopac-mq-srv/trade/buy"
	urlPlaceOrderSell                   string = "/sinopac-mq-srv/trade/sell"
	urlPlaceOrderSellFirst              string = "/sinopac-mq-srv/trade/sell_first"
	urlCancelOrder                      string = "/sinopac-mq-srv/trade/cancel"
	urlFetchOrderStatus                 string = "/sinopac-mq-srv/trade/status"
	urlFetchOrderStatusHistory          string = "/sinopac-mq-srv/trade/status-history"
	urlFetchServerKey                   string = "/sinopac-mq-srv/system/healthcheck"
	urlAskSinpacConnectMQ               string = "/sinopac-mq-srv/system/mq-connect"
	urlRestartSinopacSRV                string = "/sinopac-mq-srv/system/restart"
)
