basePath: /trade-agent
definitions:
  dbagent.Balance:
    properties:
      discount:
        type: integer
      forward:
        type: integer
      original_balance:
        type: integer
      reverse:
        type: integer
      total:
        type: integer
      trade_count:
        type: integer
      trade_day:
        type: string
    type: object
  dbagent.Stock:
    properties:
      category:
        type: string
      day_trade:
        type: boolean
      exchange:
        type: string
      last_close:
        type: number
      last_close_change_pct:
        type: number
      last_volume:
        type: integer
      name:
        type: string
      number:
        type: string
    type: object
  dbagent.Target:
    properties:
      rank:
        type: integer
      real_time_add:
        type: boolean
      stock:
        $ref: '#/definitions/dbagent.Stock'
      stock_id:
        type: integer
      trade_day:
        type: string
      volume:
        type: integer
    type: object
  handlers.ErrorResponse:
    properties:
      attachment: {}
      response:
        type: string
    type: object
info:
  contact: {}
  description: API docs for Trade Agent
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Trade Agent
  version: 2.0.0
paths:
  /balance:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: DeletaAllBalance
      tags:
      - Balance
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dbagent.Balance'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: GetAllBalance
      tags:
      - Balance
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          items:
            $ref: '#/definitions/dbagent.Balance'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: ImportBalance
      tags:
      - Balance
  /targets:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dbagent.Target'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: GetTradeDayTargets
      tags:
      - Targets
swagger: "2.0"
